/*
 * CryptoAPIs
 *
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2021-03-20
 * Contact: developers@cryptoapis.io
 * Generated by: https://openapi-generator.tech
 */

/// CreateFungibleTokenTransactionRequestFromAddressWithoutFeePriorityRist : Tron Trc20 Token



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateFungibleTokenTransactionRequestFromAddressWithoutFeePriorityRist {
    /// Defines the contract address in the blockchain for an ERC20 token.
    #[serde(rename = "contractAddress")]
    pub contract_address: String,
    /// Defines the fee limit value.
    #[serde(rename = "feeLimit")]
    pub fee_limit: String,
    /// Defines the Token symbol.
    #[serde(rename = "symbol")]
    pub symbol: String,
}

impl CreateFungibleTokenTransactionRequestFromAddressWithoutFeePriorityRist {
    /// Tron Trc20 Token
    pub fn new(contract_address: String, fee_limit: String, symbol: String) -> CreateFungibleTokenTransactionRequestFromAddressWithoutFeePriorityRist {
        CreateFungibleTokenTransactionRequestFromAddressWithoutFeePriorityRist {
            contract_address,
            fee_limit,
            symbol,
        }
    }
}


