/*
 * CryptoAPIs
 *
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2021-03-20
 * Contact: developers@cryptoapis.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateSingleTransactionRequestFromAddressWithoutFeePriorityRiRecipient {
    /// Defines the destination address.
    #[serde(rename = "address")]
    pub address: String,
    /// Defines the amount sent to the destination address.
    #[serde(rename = "amount")]
    pub amount: String,
    /// Represents the public address, which is a compressed and shortened form of a public key. The classic address is shown when the source address is an x-Address.
    #[serde(rename = "classicAddress", skip_serializing_if = "Option::is_none")]
    pub classic_address: Option<String>,
    /// Defines the unit of the recieved amount for the address.
    #[serde(rename = "unit")]
    pub unit: String,
}

impl CreateSingleTransactionRequestFromAddressWithoutFeePriorityRiRecipient {
    pub fn new(address: String, amount: String, unit: String) -> CreateSingleTransactionRequestFromAddressWithoutFeePriorityRiRecipient {
        CreateSingleTransactionRequestFromAddressWithoutFeePriorityRiRecipient {
            address,
            amount,
            classic_address: None,
            unit,
        }
    }
}


