/*
 * CryptoAPIs
 *
 * Crypto APIs 2.0 is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs 2.0 can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs 2.0 provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: developers@cryptoapis.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateAutomaticTokensForwardingRbTokenData {
    /// Represents the specific `propertyId` of the token data that will be forwarded.
    #[serde(rename = "propertyId")]
    pub property_id: i32,
    /// Represents the specific `contractAddress` of the Token that will be forwarded.
    #[serde(rename = "contractAddress")]
    pub contract_address: String,
}

impl CreateAutomaticTokensForwardingRbTokenData {
    pub fn new(property_id: i32, contract_address: String) -> CreateAutomaticTokensForwardingRbTokenData {
        CreateAutomaticTokensForwardingRbTokenData {
            property_id,
            contract_address,
        }
    }
}


