/*
 * CryptoAPIs
 *
 * Crypto APIs 2.0 is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs 2.0 can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs 2.0 provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: developers@cryptoapis.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DecodeRawTransactionHexRi {
    #[serde(rename = "blockchainSpeficicData")]
    pub blockchain_speficic_data: Box<crate::models::DecodeRawTransactionHexRis>,
    /// Represents the total size of this transaction.
    #[serde(rename = "size")]
    pub size: i32,
    /// Represents the decoded transaction hex.
    #[serde(rename = "transactionId")]
    pub transaction_id: String,
}

impl DecodeRawTransactionHexRi {
    pub fn new(blockchain_speficic_data: crate::models::DecodeRawTransactionHexRis, size: i32, transaction_id: String) -> DecodeRawTransactionHexRi {
        DecodeRawTransactionHexRi {
            blockchain_speficic_data: Box::new(blockchain_speficic_data),
            size,
            transaction_id,
        }
    }
}


