/*
 * CryptoAPIs
 *
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2021-03-20
 * Contact: developers@cryptoapis.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EstimateTransactionSmartFeeRi {
    /// Represents the confirmation target in blocks
    #[serde(rename = "confirmationTarget")]
    pub confirmation_target: i32,
    /// Represents the Fee Rate value.
    #[serde(rename = "feeRate")]
    pub fee_rate: String,
    /// Defines the fee unit.
    #[serde(rename = "unit")]
    pub unit: String,
}

impl EstimateTransactionSmartFeeRi {
    pub fn new(confirmation_target: i32, fee_rate: String, unit: String) -> EstimateTransactionSmartFeeRi {
        EstimateTransactionSmartFeeRi {
            confirmation_target,
            fee_rate,
            unit,
        }
    }
}


