/*
 * CryptoAPIs
 *
 * Crypto APIs 2.0 is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs 2.0 can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs 2.0 provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: developers@cryptoapis.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EstimateTokenGasLimitRbDataItem {
    /// Represents transactions' amount.
    #[serde(rename = "amount")]
    pub amount: String,
    /// Defines the specific token identifier.  For Ethereum-based transactions it is the contract.
    #[serde(rename = "contract")]
    pub contract: String,
    /// Represents the ERC contract type. It can be ERC20 or ERC721
    #[serde(rename = "contractType")]
    pub contract_type: String,
    /// The address which receives this transaction. In UTXO-based protocols like Bitcoin there could be several senders while in account-based protocols like Ethereum there is always only one recipient.
    #[serde(rename = "recipient")]
    pub recipient: String,
    /// Represents the address which sends this transaction. In UTXO-based protocols like Bitcoin there could be several senders while in account-based protocols like Ethereum there is always only one sender.
    #[serde(rename = "sender")]
    pub sender: String,
}

impl EstimateTokenGasLimitRbDataItem {
    pub fn new(amount: String, contract: String, contract_type: String, recipient: String, sender: String) -> EstimateTokenGasLimitRbDataItem {
        EstimateTokenGasLimitRbDataItem {
            amount,
            contract,
            contract_type,
            recipient,
            sender,
        }
    }
}


