/*
 * CryptoAPIs
 *
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2021-03-20
 * Contact: developers@cryptoapis.io
 * Generated by: https://openapi-generator.tech
 */

/// GetXrpRippleBlockDetailsByBlockHeightRiTotalCoins : Represents the total Coins of the block as a string.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetXrpRippleBlockDetailsByBlockHeightRiTotalCoins {
    /// Represents the total amount of all Coins of the block as a string.
    #[serde(rename = "amount")]
    pub amount: String,
    /// Represents the unit of total Coins of the block as a string.
    #[serde(rename = "unit")]
    pub unit: String,
}

impl GetXrpRippleBlockDetailsByBlockHeightRiTotalCoins {
    /// Represents the total Coins of the block as a string.
    pub fn new(amount: String, unit: String) -> GetXrpRippleBlockDetailsByBlockHeightRiTotalCoins {
        GetXrpRippleBlockDetailsByBlockHeightRiTotalCoins {
            amount,
            unit,
        }
    }
}


