/*
 * CryptoAPIs
 *
 * Crypto APIs 2.0 is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs 2.0 can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs 2.0 provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: developers@cryptoapis.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetHdWalletXPubYPubZPubAssetsRi {
    /// Represents fungible tokens'es detailed information
    #[serde(rename = "fungibleTokens", skip_serializing_if = "Option::is_none")]
    pub fungible_tokens: Option<Vec<crate::models::GetHdWalletXPubYPubZPubAssetsRiFungibleTokens>>,
    /// Represents non-fungible tokens'es detailed information.
    #[serde(rename = "nonFungibleTokens", skip_serializing_if = "Option::is_none")]
    pub non_fungible_tokens: Option<Vec<crate::models::GetHdWalletXPubYPubZPubAssetsRiNonFungibleTokens>>,
    #[serde(rename = "confirmedBalance")]
    pub confirmed_balance: Box<crate::models::GetHdWalletXPubYPubZPubAssetsRiConfirmedBalance>,
}

impl GetHdWalletXPubYPubZPubAssetsRi {
    pub fn new(confirmed_balance: crate::models::GetHdWalletXPubYPubZPubAssetsRiConfirmedBalance) -> GetHdWalletXPubYPubZPubAssetsRi {
        GetHdWalletXPubYPubZPubAssetsRi {
            fungible_tokens: None,
            non_fungible_tokens: None,
            confirmed_balance: Box::new(confirmed_balance),
        }
    }
}


