/*
 * CryptoAPIs
 *
 * Crypto APIs 2.0 is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs 2.0 can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs 2.0 provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: developers@cryptoapis.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetEip1559FeeRecommendationsRiMaxPriorityFeePerGas {
    /// Represents the fast maximum priority fee per gas, calculated from unconfirmed transactions.
    #[serde(rename = "fast")]
    pub fast: String,
    /// Represents the slow maximum priority fee per gas, calculated from unconfirmed transactions.
    #[serde(rename = "slow")]
    pub slow: String,
    /// Represents the standard maximum priority fee per gas, calculated from unconfirmed transactions.
    #[serde(rename = "standard")]
    pub standard: String,
    /// Represents the unit of the maximum priority fee per gas.
    #[serde(rename = "unit")]
    pub unit: String,
}

impl GetEip1559FeeRecommendationsRiMaxPriorityFeePerGas {
    pub fn new(fast: String, slow: String, standard: String, unit: String) -> GetEip1559FeeRecommendationsRiMaxPriorityFeePerGas {
        GetEip1559FeeRecommendationsRiMaxPriorityFeePerGas {
            fast,
            slow,
            standard,
            unit,
        }
    }
}


