/*
 * CryptoAPIs
 *
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2021-03-20
 * Contact: developers@cryptoapis.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetFeeRecommendationsRi {
    /// Currency unit
    #[serde(rename = "unit")]
    pub unit: String,
    /// Fast fee per byte calculated from unconfirmed transactions
    #[serde(rename = "fast")]
    pub fast: String,
    /// Slow fee per byte calculated from unconfirmed transactions
    #[serde(rename = "slow")]
    pub slow: String,
    /// Standard fee per byte calculated from unconfirmed transactions
    #[serde(rename = "standard")]
    pub standard: String,
}

impl GetFeeRecommendationsRi {
    pub fn new(unit: String, fast: String, slow: String, standard: String) -> GetFeeRecommendationsRi {
        GetFeeRecommendationsRi {
            unit,
            fast,
            slow,
            standard,
        }
    }
}


