/*
 * CryptoAPIs
 *
 * Crypto APIs 2.0 is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs 2.0 can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs 2.0 provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: developers@cryptoapis.io
 * Generated by: https://openapi-generator.tech
 */

/// ListLatestMinedBlocksRibsz2 : Zcash



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListLatestMinedBlocksRibsz2 {
    /// Represents a specific sub-unit of Zcash. Bits have two-decimal precision
    #[serde(rename = "bits")]
    pub bits: String,
    /// Represents a hexadecimal number of all the hashes necessary to produce the current chain. E.g., when converting 0000000000000000000000000000000000000000000086859f7a841475b236fd to a decimal you get 635262017308958427068157 hashes, or 635262 exahashes.
    #[serde(rename = "chainwork")]
    pub chainwork: String,
    /// Defines the single and final (root) node of a Merkle tree. It is the combined hash of all transactions' hashes that are part of a blockchain block.
    #[serde(rename = "merkleroot")]
    pub merkleroot: String,
    /// Represents a random value that can be adjusted to satisfy the proof of work
    #[serde(rename = "nonce")]
    pub nonce: String,
    /// Represents the total size of the block in Bytes.
    #[serde(rename = "size")]
    pub size: i32,
    /// Represents the transaction version number.
    #[serde(rename = "version")]
    pub version: i32,
}

impl ListLatestMinedBlocksRibsz2 {
    /// Zcash
    pub fn new(bits: String, chainwork: String, merkleroot: String, nonce: String, size: i32, version: i32) -> ListLatestMinedBlocksRibsz2 {
        ListLatestMinedBlocksRibsz2 {
            bits,
            chainwork,
            merkleroot,
            nonce,
            size,
            version,
        }
    }
}


