/*
 * CryptoAPIs
 *
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2021-03-20
 * Contact: developers@cryptoapis.io
 * Generated by: https://openapi-generator.tech
 */

/// ListLatestMinedBlocksRibsx : XRP



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListLatestMinedBlocksRibsx {
    #[serde(rename = "totalCoins", skip_serializing_if = "Option::is_none")]
    pub total_coins: Option<Box<crate::models::ListLatestMinedBlocksRibsxTotalCoins>>,
    #[serde(rename = "totalFees")]
    pub total_fees: Box<crate::models::ListLatestMinedBlocksRibsxTotalFees>,
}

impl ListLatestMinedBlocksRibsx {
    /// XRP
    pub fn new(total_fees: crate::models::ListLatestMinedBlocksRibsxTotalFees) -> ListLatestMinedBlocksRibsx {
        ListLatestMinedBlocksRibsx {
            total_coins: None,
            total_fees: Box::new(total_fees),
        }
    }
}


