/*
 * CryptoAPIs
 *
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2021-03-20
 * Contact: developers@cryptoapis.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListAllAssetsFromAllWalletsRiCoins {
    /// Represents the specific blockchain protocol name, e.g. Ethereum, Bitcoin, etc.
    #[serde(rename = "blockchain")]
    pub blockchain: String,
    /// Defines the total balance of the address that is confirmed. It doesn't include unconfirmed transactions.
    #[serde(rename = "confirmedBalance")]
    pub confirmed_balance: String,
    /// Represents the name of the blockchain network used; blockchain networks are usually identical as technology and software, but they differ in data, e.g. - \"mainnet\" is the live network with actual data while networks like \"testnet\", \"ropsten\" are test networks.
    #[serde(rename = "network")]
    pub network: String,
    /// Defines the total amount of all coins received to the address, based on confirmed transactions.
    #[serde(rename = "totalReceived")]
    pub total_received: String,
    /// Defines the total amount of all spent by this address coins, based on confirmed transactions.
    #[serde(rename = "totalSpent")]
    pub total_spent: String,
    /// Represents the unit of the confirmed balance.
    #[serde(rename = "unit")]
    pub unit: String,
}

impl ListAllAssetsFromAllWalletsRiCoins {
    pub fn new(blockchain: String, confirmed_balance: String, network: String, total_received: String, total_spent: String, unit: String) -> ListAllAssetsFromAllWalletsRiCoins {
        ListAllAssetsFromAllWalletsRiCoins {
            blockchain,
            confirmed_balance,
            network,
            total_received,
            total_spent,
            unit,
        }
    }
}


