/*
 * CryptoAPIs
 *
 * Crypto APIs 2.0 is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs 2.0 can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs 2.0 provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: developers@cryptoapis.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListAllAssetsFromAllWalletsRiFungibleTokens {
    /// Defines the amount of the fungible tokens.
    #[serde(rename = "amount")]
    pub amount: String,
    /// Represents the specific blockchain protocol name, e.g. Ethereum, Bitcoin, etc.
    #[serde(rename = "blockchain")]
    pub blockchain: String,
    /// Defines the specific token identifier. For Bitcoin-based transactions it should be the propertyId and for Ethereum-based transactions - the contract.
    #[serde(rename = "identifier")]
    pub identifier: String,
    /// Represents the name of the blockchain network used; blockchain networks are usually identical as technology and software, but they differ in data, e.g. - \"mainnet\" is the live network with actual data while networks like \"testnet\", \"ropsten\" are test networks.
    #[serde(rename = "network")]
    pub network: String,
    /// Defines the symbol of the fungible tokens.
    #[serde(rename = "symbol")]
    pub symbol: String,
    /// Defines the specific token type.
    #[serde(rename = "type")]
    pub _type: String,
}

impl ListAllAssetsFromAllWalletsRiFungibleTokens {
    pub fn new(amount: String, blockchain: String, identifier: String, network: String, symbol: String, _type: String) -> ListAllAssetsFromAllWalletsRiFungibleTokens {
        ListAllAssetsFromAllWalletsRiFungibleTokens {
            amount,
            blockchain,
            identifier,
            network,
            symbol,
            _type,
        }
    }
}


